#!/bin/bash
# =============================================================================
# OpenVEPA Docker Deployment Script
# =============================================================================
# Interactive script that configures and deploys OpenVEPA via Docker Compose.
#
# Usage:
#   ./docker/deploy.sh           # Interactive setup + deploy
#   ./docker/deploy.sh --quick   # Deploy with defaults (Ollama, no SSH)
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${PROJECT_ROOT}/.env"

echo "============================================="
echo "  OpenVEPA Docker Deployment"
echo "============================================="
echo ""

# Quick mode — use defaults
if [ "${1:-}" = "--quick" ]; then
    echo "Quick deploy with defaults..."
    cp "${SCRIPT_DIR}/.env.example" "$ENV_FILE"
    cd "$PROJECT_ROOT"
    docker compose up -d --build
    echo ""
    echo "OpenVEPA is starting..."
    echo "Open: http://localhost:8371"
    echo "If this is your first run, you'll be redirected to the setup wizard."
    exit 0
fi

# Interactive configuration
echo "Let's configure your OpenVEPA installation."
echo ""

# Provider
echo "Which AI provider would you like to use?"
echo "  1) Ollama (Local, free - recommended)"
echo "  2) OpenAI (Cloud, requires API key)"
echo ""
read -rp "Choice [1]: " provider_choice
provider_choice="${provider_choice:-1}"

PROVIDER=""
MODEL=""
API_KEY=""

if [ "$provider_choice" = "2" ]; then
    PROVIDER="openai"
    read -rp "OpenAI API Key: " -s API_KEY
    echo ""
    read -rp "Model [gpt-4o]: " MODEL
    MODEL="${MODEL:-gpt-4o}"
else
    PROVIDER="ollama"
    read -rp "Model [llama3.2]: " MODEL
    MODEL="${MODEL:-llama3.2}"
fi

# Port
read -rp "Server port [8371]: " PORT
PORT="${PORT:-8371}"

# SSH
read -rp "Enable SSH access? (y/N): " ssh_enabled
SSH_ENABLED="false"
if [[ "$ssh_enabled" =~ ^[Yy] ]]; then
    SSH_ENABLED="true"
fi

# Ollama sidecar
USE_OLLAMA_PROFILE=""
if [ "$PROVIDER" = "ollama" ]; then
    read -rp "Start Ollama in a Docker container? (Y/n): " use_ollama
    if [[ ! "$use_ollama" =~ ^[Nn] ]]; then
        USE_OLLAMA_PROFILE="--profile with-ollama"
    fi
fi

# Write .env file
cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
OPENVEPA_PORT=${PORT}
SSH_ENABLED=${SSH_ENABLED}
SSH_PORT=2222
OPENVEPA_PROVIDER=${PROVIDER}
OPENVEPA_MODEL=${MODEL}
OPENVEPA_API_KEY=${API_KEY}
OPENVEPA_OLLAMA_ENDPOINT=http://ollama:11434
OLLAMA_PORT=11434
EOF

echo ""
echo "Configuration saved to .env"
echo ""

# Summary
echo "============================================="
echo "  Deployment Summary"
echo "============================================="
echo "  Provider: ${PROVIDER}"
echo "  Model:    ${MODEL}"
echo "  Port:     ${PORT}"
echo "  SSH:      ${SSH_ENABLED}"
echo "  Ollama:   ${USE_OLLAMA_PROFILE:-standalone}"
echo "============================================="
echo ""

read -rp "Deploy now? (Y/n): " confirm
if [[ "$confirm" =~ ^[Nn] ]]; then
    echo "Deployment cancelled. Run 'docker compose up -d' when ready."
    exit 0
fi

# Build and deploy
cd "$PROJECT_ROOT"
echo "Building and starting containers..."
docker compose ${USE_OLLAMA_PROFILE} up -d --build

echo ""
echo "============================================="
echo "  OpenVEPA is starting!"
echo "============================================="
echo ""
echo "  Web UI:  http://localhost:${PORT}"
echo "  If this is your first run, you'll be redirected to the setup wizard."
if [ "$SSH_ENABLED" = "true" ]; then
    echo "  SSH:     ssh openvepa@localhost -p 2222"
fi
echo ""
echo "  View logs:  docker compose logs -f openvepa"
echo "  Stop:       docker compose down"
echo ""

# If Ollama was started, offer to pull the model
if [ -n "$USE_OLLAMA_PROFILE" ] && [ "$PROVIDER" = "ollama" ]; then
    echo "Waiting for Ollama to start..."
    sleep 5
    echo "Pulling model '${MODEL}'..."
    docker exec openvepa-ollama ollama pull "${MODEL}" || echo "WARNING: Could not pull model. Pull manually: docker exec openvepa-ollama ollama pull ${MODEL}"
fi
