namespace OpenVEPA.Core.Sessions;

/// <summary>Identifies the role of the entity that authored a message.</summary>
public enum MessageRole
{
    /// <summary>Message sent by the end user.</summary>
    User,

    /// <summary>Message generated by the assistant.</summary>
    Assistant,

    /// <summary>System-level instruction or context.</summary>
    System,

    /// <summary>Output produced by a tool or skill invocation.</summary>
    Tool
}
